### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by plongitudes** [Namorzyny/NerdFontsForBlink#1]
I've been fighting with getting NF fonts working with Blink for a couple of weeks on and off, kept hitting one issue or another. I just stumbled across your repo and wanted to say thanks for putting this out into the world! My Blink Shell install is now very happy. :)

**Comment by namorzyny** [comment]
@plongitudes Thank you for your kind words! I'm glad to hear that my work was helpful for you. :)
